### ISSUE TITLE
Git Time Metric executable is out of date

### ISSUE THREAD

**Issue by OfficeYA** [git-time-metric/gtm-jetbrains-plugin#8]
Hi there

I am using rubymine version 2017.3.2

I just installed the newest version of GTM from: **https://github.com/git-time-metric/gtm/releases/tag/v1.2.11**, I did follow the instructions, set the paths and so on.

I get the message _Git Time Metric executable is out of date_ and it does not record anything.

Any idea about how to make it work?

**Comment by dnedrow** [comment]
Hi.

If you're on a *nix system, including MacOS, open a terminal and execute the following commands:
`which gtm`
`gtm -v`

What is returned from those commands? They should tell you which `gtm` executable is found first on your path, and what version that executable is.

The JetBrains plugin only looks in specific locations for the `gtm` executable. On Windows, that is:
`%PATH%;\ProgramFiles\gtm;\ProgramFiles(x86)\gtm;<homedir>\gtm`
and on *nix-based systems, including MacOS:
`$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:~/bin:~/local/bin`

Which version of the "Git Time Metric" plugin do you have installed in RubyMine? I believe the current version is 1.0.13.

**Comment by OfficeYA** [comment]
Hi! thanks 4 ur soon answer

I am using Linux. 

These are the output of the commands:

`addicttux@amd8 ~ $ which gtm`
`/home/addicttux/bin/gtm/gtm`
`addicttux@amd8 ~ $ gtm -v`
`v1.2.11`

I am going to try the paths that u pointed in your comment.

**Comment by OfficeYA** [comment]
Ok, I moved gtm to /usr/bin and it worked fine.

Thanks.
